[project]
name = "swegov-opendata"
version = "0.1.1"
description = "Data models for handling Swedish riksdagens öppna data (open data)"
readme = "README.md"
requires-python = ">= 3.11"
license = "MIT"
authors = [
  { name = "Språkbanken", email = "sb-info@svenska.gu.se" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  # "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Operating System :: MacOS",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX",
  "Operating System :: Unix",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
  # "uncomment if you test on these interpreters:",
  # "Programming Language :: Python :: Implementation :: IronPython",
  # "Programming Language :: Python :: Implementation :: Jython",
  # "Programming Language :: Python :: Implementation :: Stackless",
  "Topic :: Utilities",
  "Typing :: Typed",
]
dependencies = [
  "pydantic>=2.12.5",
]

[project.urls]
Changelog = "https://github.com/spraakbanken/swegov-opendata-py/blob/main/CHANGELOG.md"
Homepage = "https://spraakbanken.se"
Issues = "https://github.com/spraakbanken/swegov-opendata-py/issues"
Repository = "https://github.com/spraakbanken/swegov-opendata-py"

[dependency-groups]
dev = [{ include-group = "lint" }, { include-group = "test" }]
lint = [
  "ruff>=0.16.9",
  "ty>=0.0.84",
]
test = [
  "pytest>=9.0.3",
  "pytest-cov>=7.0.0",
  "syrupy>=6.0.0",
]

[build-system]
requires = ["uv_build>=0.12,<0.13"]
build-backend = "uv_build"

[tool.uv]
exclude-newer = "P7D"
