[project]
name = "swegov-opendata"
version = "0.1.0"
description = "Preprocessing of Swedish riksdagens öppna data (open data)"
readme = "README.md"
requires-python = ">= 3.10"
license = { text = "MIT" }
authors = [
  { name = "Språkbanken Text", email = "sb-info@svenska.gu.se" },
]
dependencies = [
  "beautifulsoup4>=4.12.2",
  "lxml>=4.9.3",
  "trafilatura>=2.0.0",
  "typer>=0.9.0",
]

[dependency-groups]
dev = [{ include-group = "lint" }, { include-group = "test" }]
lint = [
  "ruff>=0.15.1",
  "ty>=0.0.17",
]
test = [
  "pytest>=8.4.2",
  "pytest-cov>=7.0.0",
]

[build-system]
requires = ["uv_build>=0.10,<0.11"]
build-backend = "uv_build"
